version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: SchoolManagement
      MYSQL_PASSWORD: admin655
      MYSQL_ROOT_PASSWORD: admin655
    expose:
      - 3308
    volumes:
      - ./:/usr/src/app

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
          - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - SQLALCHEMY_DATABASE_URL=f'mysql+mysqlconnector://{settings.database_username}:{settings.database_password}@{settings.database_hostname}:{settings.database_port}/{settings.database_name}'
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    restart: always